change github workflow to fail if any pytest fails

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -51,10 +51,14 @@ jobs:
       - name: Test with pytest Poetry
         run: |
           poetry run pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=sources Webapp/tests | tee pytest-coverage.txt
-        continue-on-error: false  # Explicitly set to false to stop the job if tests fail
+        continue-on-error: true  # Explicitly set to false to stop the job if tests fail
 
       - name: Pytest coverage comment
         uses: MishaKav/pytest-coverage-comment@main
         with:
           pytest-coverage-path: pytest-coverage.txt
           junitxml-path: pytest.xml
+
+      - name: Fail the job if pytest failed
+        if: steps.pytest.outcome != 'success'
+        run: exit 1
